/* auto-generated by process_erp.py */
window.ERP_DATA = {
  "meta": {
    "sample": false,
    "partial": false,
    "note": "ข้อมูลจริงจาก raw export (Pojjaman ERP). สร้างโดย process_erp.py",
    "updated": "2026-07-14T10:06:53+07:00",
    "period_ytd": "01/01/2026 - 14/07/2026",
    "source": "Pojjaman ERP (aagc.on.lk) — raw export",
    "org": "ทุกโปรเจกต์",
    "currency": "THB"
  },
  "kpi": {
    "stock_value": 249276498.38,
    "stock_qty": 5223890.53,
    "sales_receipt_ytd": 401502005.07,
    "receipt_count": 323,
    "receipt_retention": 16510065.35,
    "ar_outstanding": null,
    "po_ytd": 186613875.39,
    "gr_ytd": 200752016.39,
    "gr_outstanding": null
  },
  "months": [
    "ม.ค.",
    "ก.พ.",
    "มี.ค.",
    "เม.ย.",
    "พ.ค.",
    "มิ.ย.",
    "ก.ค."
  ],
  "sales_monthly": {
    "receipt": [
      52740472.3,
      65204016.77,
      68577962.91,
      102133507.93,
      38003097.85,
      64988290.23,
      9854657.08
    ]
  },
  "purchase_monthly": {
    "po": [
      24681871.57,
      35174115.29,
      39012307.22,
      33162152.19,
      29970972.32,
      19652025.38,
      4960431.42
    ],
    "gr": [
      28600201.46,
      35408828.12,
      36824780.02,
      35885724.24,
      28831483.71,
      27493494.46,
      7707504.37
    ]
  },
  "stock_monthly": {
    "value": null,
    "qty": null
  },
  "top_suppliers": [
    {
      "name": "บริษัท ฟีนิกซ์ กลาส จำกัด",
      "po": 15230571.01,
      "gr": 0
    },
    {
      "name": "บริษัท มุกดาสยาม อลูมิเนียม แอ",
      "po": 11959091.0,
      "gr": 0
    },
    {
      "name": "บริษัท เซ็นไดสตีล จำกัด",
      "po": 11898107.4,
      "gr": 0
    },
    {
      "name": "บริษัท เฮ้งชัยแสงเทรดดิ้ง (198",
      "po": 9827786.53,
      "gr": 0
    },
    {
      "name": "บริษัท แสงเจริญพัฒนาเอ็นเตอร์ไ",
      "po": 6792650.0,
      "gr": 0
    },
    {
      "name": "บริษัท เรย์นาร์ส อะลูมิเนียม จ",
      "po": 6287740.0,
      "gr": 0
    }
  ]
};
